name: oracle
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - ipykernel
  - nb_conda_kernels
  - jupyterlab
  - matplotlib
  - beautifulsoup4
  - certifi
  - chardet
  - idna
  - requests
  - urllib3
